// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package mock_page is a generated GoMock package.
package mock_page

import (
	reflect "reflect"

	page "github.com/Hives-project/HivePages/pkg/page"
	gomock "github.com/golang/mock/gomock"
)

// MockPageRepository is a mock of PageRepository interface.
type MockPageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPageRepositoryMockRecorder
}

// MockPageRepositoryMockRecorder is the mock recorder for MockPageRepository.
type MockPageRepositoryMockRecorder struct {
	mock *MockPageRepository
}

// NewMockPageRepository creates a new mock instance.
func NewMockPageRepository(ctrl *gomock.Controller) *MockPageRepository {
	mock := &MockPageRepository{ctrl: ctrl}
	mock.recorder = &MockPageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPageRepository) EXPECT() *MockPageRepositoryMockRecorder {
	return m.recorder
}

// CreatePage mocks base method.
func (m *MockPageRepository) CreatePage(page page.GetPage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePage", page)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePage indicates an expected call of CreatePage.
func (mr *MockPageRepositoryMockRecorder) CreatePage(page interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePage", reflect.TypeOf((*MockPageRepository)(nil).CreatePage), page)
}

// GetPageByUuid mocks base method.
func (m *MockPageRepository) GetPageByUuid(uuid string) (page.GetPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPageByUuid", uuid)
	ret0, _ := ret[0].(page.GetPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPageByUuid indicates an expected call of GetPageByUuid.
func (mr *MockPageRepositoryMockRecorder) GetPageByUuid(uuid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPageByUuid", reflect.TypeOf((*MockPageRepository)(nil).GetPageByUuid), uuid)
}

// GetPages mocks base method.
func (m *MockPageRepository) GetPages() ([]page.GetPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPages")
	ret0, _ := ret[0].([]page.GetPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPages indicates an expected call of GetPages.
func (mr *MockPageRepositoryMockRecorder) GetPages() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPages", reflect.TypeOf((*MockPageRepository)(nil).GetPages))
}
