// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package mock_page is a generated GoMock package.
package mock_page

import (
	reflect "reflect"

	page "github.com/Hives-project/HivePages/pkg/page"
	gomock "github.com/golang/mock/gomock"
)

// MockPageService is a mock of PageService interface.
type MockPageService struct {
	ctrl     *gomock.Controller
	recorder *MockPageServiceMockRecorder
}

// MockPageServiceMockRecorder is the mock recorder for MockPageService.
type MockPageServiceMockRecorder struct {
	mock *MockPageService
}

// NewMockPageService creates a new mock instance.
func NewMockPageService(ctrl *gomock.Controller) *MockPageService {
	mock := &MockPageService{ctrl: ctrl}
	mock.recorder = &MockPageServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPageService) EXPECT() *MockPageServiceMockRecorder {
	return m.recorder
}

// CreatePage mocks base method.
func (m *MockPageService) CreatePage(page page.GetPage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePage", page)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePage indicates an expected call of CreatePage.
func (mr *MockPageServiceMockRecorder) CreatePage(page interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePage", reflect.TypeOf((*MockPageService)(nil).CreatePage), page)
}

// GetPageByUuid mocks base method.
func (m *MockPageService) GetPageByUuid(uuid string) (page.GetPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPageByUuid", uuid)
	ret0, _ := ret[0].(page.GetPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPageByUuid indicates an expected call of GetPageByUuid.
func (mr *MockPageServiceMockRecorder) GetPageByUuid(uuid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPageByUuid", reflect.TypeOf((*MockPageService)(nil).GetPageByUuid), uuid)
}

// GetPages mocks base method.
func (m *MockPageService) GetPages() ([]page.GetPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPages")
	ret0, _ := ret[0].([]page.GetPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPages indicates an expected call of GetPages.
func (mr *MockPageServiceMockRecorder) GetPages() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPages", reflect.TypeOf((*MockPageService)(nil).GetPages))
}
